dist: xenial
language: rust
cache: cargo
rust:
- 1.34.2
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
  include:
  - rust: stable
    env: "MINVER=true"
install:
- rustup component add rustfmt
- if [[ ! -e $TRAVIS_HOME/.cargo/bin/cargo-sweep ]]; then cargo install --version 0.4.1 cargo-sweep; fi
before_script:
- cargo sweep -s
script:
- .travis/build.sh
before_cache:
- cargo sweep -f
